/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountAllEntries: typeof import('./components/pages/AccountAllEntries.vue')['default']
    AccountBalanceSheet: typeof import('./components/pages/AccountBalanceSheet.vue')['default']
    AccountCustomerList: typeof import('./components/pages/AccountCustomerList.vue')['default']
    AccountCustomerPortfolio: typeof import('./components/pages/AccountCustomerPortfolio.vue')['default']
    AccountGroupAndLedger: typeof import('./components/pages/AccountGroupAndLedger.vue')['default']
    AccountGSTReports: typeof import('./components/pages/AccountGSTReports.vue')['default']
    AccountInvoiceReturn: typeof import('./components/pages/AccountInvoiceReturn.vue')['default']
    AccountProfitAndLoss: typeof import('./components/pages/AccountProfitAndLoss.vue')['default']
    AccountPurchaseBill: typeof import('./components/pages/AccountPurchaseBill.vue')['default']
    AccountSalesInvoice: typeof import('./components/pages/AccountSalesInvoice.vue')['default']
    AccountSettings: typeof import('./components/pages/AccountSettings.vue')['default']
    AccountUserRolePermission: typeof import('./components/pages/AccountUserRolePermission.vue')['default']
    AccountVendorsList: typeof import('./components/pages/AccountVendorsList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DynamicDataTable: typeof import('./components/DynamicDataTable.vue')['default']
    ExampleApiUsage: typeof import('./components/ExampleApiUsage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IncomeRow: typeof import('./components/core/IncomeRow.vue')['default']
    InvoicePreview: typeof import('./components/pages/InvoicePreview.vue')['default']
    MenuNavigationDrawer: typeof import('./components/navigation/MenuNavigationDrawer.vue')['default']
    ProductsPage: typeof import('./components/pages/ProductsPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenInput: typeof import('./components/TokenInput.vue')['default']
    TreeItem: typeof import('./components/core/TreeItem.vue')['default']
  }
}
